ERROR_CODES = {
    "CLM-DAO-001": "Table not found",
    "CLM-DAO-002": "Write failure",
    "CLM-DAO-003": "Failed to read input data",
    "CLM-DAO-004": "Failed to create table",
    "CLM-DAO-005": "Failed to connect or create schema",
    "CLM-DAO-006": "Duplicate records found",
    "CLM-DAO-007": "Error during data transformation",
    "CLM-VAL-001": "Invalid claim",
    "CLM-RULE-001": "Required field is missing",
    "CLM-RULE-002": "Invalid datatype detected",
    "CLM-RULE-003": "Invalid date format detected",
    "CLM-RULE-004": "Invalid procedure-diagnosis mapping",
    "CLM-RULE-005": "Invalid code format detected",
    "CLM-ML-001": "Model training failed",
    "CLM-ML-002": "Model evaluation failed",
    "CLM-ML-003": "Failed to generate SHAP values",
    "CLM-ML-004": "Failed during SHAP intensity mapping",
    "CLM-ML-005": "Failed to generate claim explanations",
    "CLM-ML-006": "SHAP explanation pipeline execution failed",
    "CLM-ML-007": "Failed to load training dataset",
    "CLM-ML-008": "Failed during data preprocessing",
    "CLM-ML-009": "Failed during train-test split",
    "CLM-ML-010": "Optuna hyperparameter optimization failed",
    "CLM-ML-011": "Model training failed",
    "CLM-ML-012": "Model evaluation failed",
    "CLM-ML-013": "MLFlow logging failed",
    "CLM-ML-014": "ML pipeline execution failed",
    "CLM-LLM-001": "Failed to parse SHAP values for LLM input",
    "CLM-LLM-002": "Failed to construct prompt for LLM",
    "CLM-LLM-003": "Failed to generate explanations from LLM",
    "CLM-TRF-001": "Provider not found",
    "CLM-TRF-002": "Diagnosis not found",
    "CLM-TRF-003": "Cost benchmark not found",
    "CLM-ML-015": "Prediction failed"
}